# Generated by Django 5.1.3 on 2024-12-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_task_created_task_position_alter_task_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
